alitonia/multi-choice-system

- frontend/src/App.js
- frontend/src/pages/Home/HomePage.js
- frontend/src/pages/Placeholder.js
- frontend/src/pages/routes.js
In the light of https://github.com/alitonia/multi-choice-system/issues/15, initialize router.
> add router to frontend

- .github/workflows/projectcard-autolabel.yml
* This feature allows auto-labeling issues based on which column its linked card is in.
> add labeling based on card column

- .github/workflows/projectcard-autolabel.yml
* Update mis-configuration (invalid JSON config)
> update config string for auto-labeling

- .github/workflows/projectcard-autolabel.yml
* Again fix JSON parsing for auto-labeling
> another fix for json parse

- .github/card-labeler.yml
- .github/workflows/projectcard-autolabel.yml
* Change action because the old one does not work
> change action usage

- README.md
* Update readme for changes in api in #13
> add doc for change in backend api in #13

- .github/workflows/request-review.yml
* Auto request review when pull request is made against main branch
> add reviewer automation

- documentation/.gitignore
- frontend/src/GlobalStyles.js
> Frontend: Global styles

- frontend/src/GlobalStyles.js
- frontend/src/components/footer/Footer.styles.js
- frontend/src/components/header/Header.styles.js
- frontend/src/index.js
- frontend/src/pages/Dashboard/Exam.styles.js
- frontend/src/pages/Dashboard/MainView.styles.js
> update color var from GlobalStyles

- frontend/src/components/LoginPanel/LoginPanel.styles.js
- frontend/src/pages/LoginPage/LoginPage.styles.js
> fix login page form height

- backend/src/app/api/account/router.py
- backend/src/app/schemas/account.py
- backend/src/app/services/account_service.py
- backend/src/app/utils/decrypt_encrypt_service.py
* No PUT, POST on account
* add PUT, POST, enable and disable of account
> finish account service

- README.md
> Update README.md to contain drive links to documentation

- backend/src/app/services/account_service.py
* Change date_of_birth from '%Y-%m-%d' to '%d-%m-%Y'
* date_of_birth is of format '%Y-%m-%d'
* date_of_birth is of format '%d-%m-%Y'
* 
* Change made in accordance with https://github.com/alitonia/multi-choice-system/pull/82#discussion_r771885672
> Update account date_of_birth format

- backend/src/app/api/exam/router.py
- backend/src/app/api/routers.py
- backend/src/app/models/exam.py
- backend/src/app/models/examiner.py
- backend/src/app/services/exam_service.py
- docker_data/db-config/2-fill-data.sql
- docker_data/db-config/4-exam-test-data.sql
* Add gets for exam
* add fake exam db filler
> Exam Get service

- backend/src/app/api/exam/router.py
- backend/src/app/services/exam_service.py
* Add GETs for participants in an exam. ex: GET /exam/get_examinees?exam_id = 1
> participant get api

- frontend/src/components/header/Header.js
* keep access_token in localStorage after logout
* Remove access_token
> clean logout: remove access_token in local storage

- frontend/src/index.css
- frontend/src/pages/404/404.js
- frontend/src/pages/404/404.scss
- frontend/src/pages/routes.js
- frontend/src/utils/isLoggedIn.js
* Not found page is redirected to 404
> add 404 page

- backend/src/app/api/exam_analytic/router.py
- backend/src/app/services/exam_analytic_service.py
- frontend/src/pages/ExamStatistic/ExamStatistic.css
- frontend/src/pages/ExamStatistic/index.js
> Add choice distribution graphs

- frontend/src/components/header/Header.js
- frontend/src/components/header/Header.styles.js
- frontend/src/pages/Dashboard/MainView.js
> search exam + logo change

- frontend/src/pages/Dashboard/MainView.js
> search status
